spring:
  application:
    name: springdatajpa

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: like
    password: lion
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

